name: Build Docker Image

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted-bahn-runner

    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Docker Buildx for multiple arch builds
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          tags: norris1z/bahn:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          push: true
